@startuml
class BenefactorAnalyticsService {
    + BenefactorAnalyticsService(contextFactory:IDbContextFactory<ApplicationDbContext>, openAIService:OpenAIService)
    + <<async>> GetAnalyticsAsync(userId:string) : Task<BenefactorAnalyticsResult>
}
class BenefactorAnalyticsResult {
    + AISummary : string <<get>> <<set>>
    + DebugInfo : string <<get>> <<set>>
}
class "Dictionary`2"<T1,T2> {
}
BenefactorAnalyticsResult o-> "ScholarshipApplicantCounts<string,int>" "Dictionary`2"
BenefactorAnalyticsResult o-> "ScholarshipStatusCounts<string,Dictionary<string, int>>" "Dictionary`2"
BenefactorAnalyticsResult o-> "TotalStatusCounts<string,int>" "Dictionary`2"
BenefactorAnalyticsResult o-> "MonthlyApplicationTrends<string,int>" "Dictionary`2"
BenefactorAnalyticsResult o-> "SemesterlyApplicationTrends<string,int>" "Dictionary`2"
@enduml
