@startuml
class ScrapingBackgroundService {
    + ScrapingBackgroundService(serviceProvider:IServiceProvider, logger:ILogger<ScrapingBackgroundService>)
}
BackgroundService <|-- ScrapingBackgroundService
@enduml
