version: '3.8'

services:
  eskolar-app:
    build: .
    container_name: eskolar_app
    ports:
      - "80:80"
      # Uncomment below to enable HTTPS in development (see README for setup)
      # - "443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${AZURE_SQL_CONNECTION_STRING}
      # Uncomment below for HTTPS support (see README for setup)
      # - ASPNETCORE_URLS=https://+;http://+
      # - ASPNETCORE_Kestrel__Certificates__Default__Password=<YOUR_CERT_PASSWORD>
      # - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    # Uncomment below to mount your dev certificate for HTTPS
    # volumes:
    #   - ${USERPROFILE}/.aspnet/https:/https/
    restart: unless-stopped