@startuml
class RegisterViewModel {
    + FirstName : string <<get>> <<set>>
    + MiddleName : string <<get>> <<set>>
    + LastName : string <<get>> <<set>>
    + Sex : string <<get>> <<set>>
    + Nationality : string <<get>> <<set>>
    + PermanentAddress : string <<get>> <<set>>
    + MobileNumber : string <<get>> <<set>>
    + Email : string <<get>> <<set>>
    + Password : string <<get>> <<set>>
    + AgreeToTerms : bool <<get>> <<set>>
}
RegisterViewModel --> "DateOfBirth" DateTime
RegisterViewModel o-> "UserRole" UserRole
@enduml
