@startuml
class AnnouncementRecommendationService {
    + AnnouncementRecommendationService(context:ApplicationDbContext, userManager:UserManager<IdentityUser>)
    + <<async>> GetAnnouncementRecommendationsAsync(user:IdentityUser, query:string) : Task<List<AnnouncementRecommendation>>
}
class AnnouncementRecommendation {
    + RelevanceScore : int <<get>> <<set>>
}
enum AnnouncementQueryType {
    Institution,
    Application,
    Grants,
    Pinned,
    Benefactor,
    All,
    General,
}
class "List`1"<T> {
}
AnnouncementRecommendation o-> "Announcement" Announcement
AnnouncementRecommendation o-> "MatchReasons<string>" "List`1"
AnnouncementRecommendation --> "QueryType" AnnouncementQueryType
@enduml
