@startuml
class QueryClassificationService {
    + IsScholarshipRelatedQuery(userMessage:string) : bool
    + IsProgressTrackingQuery(userMessage:string) : bool
    + IsDocumentGuidanceQuery(userMessage:string) : bool
    + IsDeadlineQuery(userMessage:string) : bool
    + IsFinancialNeedsQuery(userMessage:string) : bool
    + IsAnnouncementRelatedQuery(userMessage:string) : bool
    + IsBenefactorQuery(userMessage:string) : bool
    + IsInstitutionQuery(userMessage:string) : bool
    + IsNameQuery(userMessage:string) : bool
    + IsFullNameQuery(userMessage:string) : bool
}
@enduml
