@startuml
class ScholarshipRecommendationService {
    + ScholarshipRecommendationService(context:ApplicationDbContext, userManager:UserManager<IdentityUser>)
    + <<async>> GetScholarshipRecommendationsAsync(user:IdentityUser) : Task<List<ScholarshipRecommendation>>
}
class ScholarshipRecommendation {
    + MatchScore : int <<get>> <<set>>
}
class "List`1"<T> {
}
ScholarshipRecommendation o-> "Scholarship" Scholarship
ScholarshipRecommendation o-> "MatchReasons<string>" "List`1"
@enduml
