@startuml
class BenefactorAdminProfile {
    + BenefactorAdminProfileId : int <<get>> <<set>>
    + UserId : string <<get>> <<set>>
    + FullName : string? <<get>> <<set>>
    + Address : string? <<get>> <<set>>
    + ContactNumber : string? <<get>> <<set>>
    + BenefactorId : int <<get>> <<set>>
    + Position : string? <<get>> <<set>>
    + ProfilePicture : string? <<get>> <<set>>
}
BenefactorAdminProfile --> "BirthDate" DateTime
BenefactorAdminProfile o-> "Benefactor" Benefactor
@enduml
