@startuml
class Scholarship {
    + ScholarshipId : int <<get>> <<set>>
    + <<required>> Title : string <<get>> <<set>>
    + Description : string? <<get>> <<set>>
    + <<required>> Benefits : string <<get>> <<set>>
    + MonetaryValue : decimal? <<get>> <<set>>
    + Requirements : string? <<get>> <<set>>
    + SlotsAvailable : int? <<get>> <<set>>
    + MinimumGPA : decimal? <<get>> <<set>>
    + RequiredCourse : string? <<get>> <<set>>
    + RequiredYearLevel : int? <<get>> <<set>>
    + RequiredUniversity : string? <<get>> <<set>>
    + IsActive : bool <<get>> <<set>> = true
    + IsInternal : bool <<get>> <<set>> = false
    + ExternalApplicationUrl : string? <<get>> <<set>>
    + RequiresExternalApplication : bool <<get>>
}
class "ICollection`1"<T> {
}
Scholarship o-> "Photos<Photo>" "ICollection`1"
Scholarship --> "ApplicationDeadline" DateTime
Scholarship o-> "CreatedAt" DateTime
Scholarship --> "UpdatedAt" DateTime
Scholarship --> "BenefactorProfileId" Guid
Scholarship --> "InstitutionProfileId" Guid
Scholarship --> "Benefactor" BenefactorProfile
Scholarship --> "Institution" InstitutionProfile
Scholarship o-> "Applications<ScholarshipApplication>" "ICollection`1"
@enduml
