@startuml
class ScholarshipGrant {
    + GrantId : int <<get>> <<set>>
    + ScholarshipId : int <<get>> <<set>>
    + StudentId : int <<get>> <<set>>
    + Status : string? <<get>> <<set>>
}
ScholarshipGrant o-> "Scholarship" Scholarship
ScholarshipGrant --> "AwardedDate" DateTime
@enduml
