@startuml
class User {
    + UserId : string <<get>> <<set>>
    + Email : string <<get>> <<set>> = ""
    + PasswordHash : string <<get>> <<set>> = ""
    + RoleId : int <<get>> <<set>>
    + IsVerified : bool <<get>> <<set>> = false
}
User o-> "Role" Role
User o-> "CreatedAt" DateTime
@enduml
