@startuml
class InstitutionProfile {
    + <<required>> UserId : string <<get>> <<set>>
    + <<required>> AdminFirstName : string <<get>> <<set>>
    + AdminMiddleName : string? <<get>> <<set>>
    + <<required>> AdminLastName : string <<get>> <<set>>
    + AdminFullName : string <<get>>
    + AdminPosition : string? <<get>> <<set>>
    + <<required>> InstitutionName : string <<get>> <<set>>
    + InstitutionType : string? <<get>> <<set>>
    + Address : string? <<get>> <<set>>
    + ContactNumber : string? <<get>> <<set>>
    + Website : string? <<get>> <<set>>
    + ContactEmail : string? <<get>> <<set>>
    + Mission : string? <<get>> <<set>>
    + Description : string? <<get>> <<set>>
    + Logo : string? <<get>> <<set>>
    + ProfilePicture : string? <<get>> <<set>>
    + AdminValidationDocument : string? <<get>> <<set>>
    + GovernmentIdDocument : string? <<get>> <<set>>
    + AuthorizationLetterDocument : string? <<get>> <<set>>
    + TotalStudents : int? <<get>> <<set>>
    + Accreditation : string? <<get>> <<set>>
    + IsVerified : bool <<get>> <<set>> = false
    + VerificationStatus : string? <<get>> <<set>> = "Pending"
    + AccountStatus : string <<get>> <<set>> = "Active"
}
class "ICollection`1"<T> {
}
InstitutionProfile --> "InstitutionProfileId" Guid
InstitutionProfile --> "EstablishedDate" DateTime
InstitutionProfile --> "VerificationDate" DateTime
InstitutionProfile o-> "CreatedAt" DateTime
InstitutionProfile --> "UpdatedAt" DateTime
InstitutionProfile o-> "ManagedScholarships<Scholarship>" "ICollection`1"
@enduml
